Update/kelola akun
Chillrend/SIMBKM pull request #5
Opened 2023-10-17 02:30 UTC by bayun2445

added button edit and delete
added new functions in RegisterConroller
created edit-akun page

2023-11-06 11:07 UTC, rinalditoryanari commented
feature edit + delete for kelola akun in admin -> approve

2023-11-06 11:28 UTC, rinalditoryanari commented
Logbook
1. kalo udah di save, file nya tidak muncul di sisi mhsw (baik tampilan detail atau edit)
   - dospen nya bisa lihat, tapi mhsw nya gak bisa
   - pi nya gak bisa liat

Laporan + Sertif
2. dokumen sama sertif gak bisa dibuka samsek

2023-11-06 11:28 UTC, rinalditoryanari requested changes
Logbook
1. kalo udah di save, file nya tidak muncul di sisi mhsw (baik tampilan detail atau edit)
   - dospen nya bisa lihat, tapi mhsw nya gak bisa
   - pi nya gak bisa liat

Laporan + Sertif
2. dokumen sama sertif gak bisa dibuka samsek

2023-11-07 07:12 UTC, bayun2445 commented
- Added view logbook feeature for Pembimbing Industri
- Moved view dokumen logbook for Mahasiswa from edit to detail page 
- Added update dokumen form in edit logbook page

2023-11-08 06:51 UTC, rinalditoryanari commented
done

2023-11-08 06:51 UTC, rinalditoryanari approved these changes

2023-11-09 01:54 UTC, Chillrend commented
lgtm

2023-11-09 01:54 UTC, merged